name: Engine coverage

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
    - uses: actions/checkout@v3

    - name: Setup .NET 8.0
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.101

    - name: Restore dependencies
      working-directory: ./Engine
      run: dotnet restore

    - name: Build
      working-directory: ./Engine
      run: dotnet build --no-restore

    - name: Install dotnet-coverage
      run: dotnet tool install --global dotnet-coverage

    - name: Test with coverage
      working-directory: ./Engine
      run: dotnet-coverage collect -f cobertura -s coverage.settings.xml -o "coverage.cobertura.xml" "dotnet test"

    - name: Upload coverage to codecov
      uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: Engine/coverage.cobertura.xml
        name: Friflo.Engine.ECS

    