name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET 3.1
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.417
#   - name: Setup .NET 5.0
#     uses: actions/setup-dotnet@v1
#     with:
#       dotnet-version: 5.0.406
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore --framework netcoreapp3.1
    - name: Test
      run: dotnet test --no-build --verbosity normal --filter FullyQualifiedName~Friflo.Json.Tests.Common
