name: CD

on:
  push:
    tags:
    - 'v*'
  
env:
  PACKAGE_DIRECTORY: ${{ github.workspace }}/output

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET 6.0
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.405
    - name: Restore dependencies
      run: dotnet restore

    - name: GetVersion
      id: version
      uses: battila7/get-version-action@v2

    - name: Build
      run: |
        echo "GITHUB_ACTIONS=true" >> $GITHUB_ENV
        dotnet build --no-restore /p:Version=${{ steps.version.outputs.version-without-v }} /p:FileVersion=${{ steps.version.outputs.version-without-v }} /p:AssemblyVersion=${{ steps.version.outputs.version-without-v }} -c Release

    - name: Test
      run: dotnet test --no-build --verbosity normal -c Release

    - name: Pack
      run: dotnet pack --no-restore --no-build -p:PackageVersion=${{ steps.version.outputs.version-without-v }} -p:SymbolPackageFormat=snupkg -p:PackageOutputPath=${{ env.PACKAGE_DIRECTORY }} -c Release

    - name: Push
      run: |
        dotnet nuget push ${{ env.PACKAGE_DIRECTORY }}/Friflo.Json.Burst.${{ steps.version.outputs.version-without-v }}.nupkg                --source https://api.nuget.org/v3/index.json -k ${{ secrets.NUGET_AUTH_TOKEN }}
        dotnet nuget push ${{ env.PACKAGE_DIRECTORY }}/Friflo.Json.Fliox.${{ steps.version.outputs.version-without-v }}.nupkg                --source https://api.nuget.org/v3/index.json -k ${{ secrets.NUGET_AUTH_TOKEN }}
        dotnet nuget push ${{ env.PACKAGE_DIRECTORY }}/Friflo.Json.Fliox.Annotation.${{ steps.version.outputs.version-without-v }}.nupkg     --source https://api.nuget.org/v3/index.json -k ${{ secrets.NUGET_AUTH_TOKEN }}
        dotnet nuget push ${{ env.PACKAGE_DIRECTORY }}/Friflo.Json.Fliox.Hub.${{ steps.version.outputs.version-without-v }}.nupkg            --source https://api.nuget.org/v3/index.json -k ${{ secrets.NUGET_AUTH_TOKEN }}
        dotnet nuget push ${{ env.PACKAGE_DIRECTORY }}/Friflo.Json.Fliox.Hub.AspNetCore.${{ steps.version.outputs.version-without-v }}.nupkg --source https://api.nuget.org/v3/index.json -k ${{ secrets.NUGET_AUTH_TOKEN }}
        dotnet nuget push ${{ env.PACKAGE_DIRECTORY }}/Friflo.Json.Fliox.Hub.Cosmos.${{ steps.version.outputs.version-without-v }}.nupkg     --source https://api.nuget.org/v3/index.json -k ${{ secrets.NUGET_AUTH_TOKEN }}
        dotnet nuget push ${{ env.PACKAGE_DIRECTORY }}/Friflo.Json.Fliox.Hub.Explorer.${{ steps.version.outputs.version-without-v }}.nupkg   --source https://api.nuget.org/v3/index.json -k ${{ secrets.NUGET_AUTH_TOKEN }}
        dotnet nuget push ${{ env.PACKAGE_DIRECTORY }}/Friflo.Json.Fliox.Hub.GraphQL.${{ steps.version.outputs.version-without-v }}.nupkg    --source https://api.nuget.org/v3/index.json -k ${{ secrets.NUGET_AUTH_TOKEN }}

    
